version: 2.1

jobs:
  build:
    docker:
      - image: node:latest

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Build Package
          command: npm run build

      - run:
          name: Set NPM Auth Token
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc

      - run:
          name: Set Github Auth Token
          command: |
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_AUTH_TOKEN}" >> ~/.npmrc

      - run:
          name: Publish to NPM Registry
          command: npm publish --registry https://registry.npmjs.org --access public

      - run:
          name: Change the Package name in Package.json
          command: |
            sudo apt install sed && $ sed -i '2s/"outers"/"@${GITHUB_REPO_NAME}\/outers"/' package.json
      
      - run:
          name: Publish to Github Package Registry
          command: npm publish --registry=https://npm.pkg.github.com --scope=@${GITHUB_REPO_NAME} --access public

workflows:
  version: 2
  Registry_Publish_Workflow:
    jobs:
      - build:
          name: Publish To NPM  & Github Package Registry
          filters:
            branches:
              only:
                - main
