name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Project
        run: npm run build
      
      - name: Run Tests
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js and NPM Config
        run: |
          npm config set registry https://npm.pkg.github.com/
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_PACK_TOKEN }}" > ~/.npmrc
      - run: npm ci
      - run: npm publish
